name: Primeiro workflow  
on:
  push:
    branches:
      - main  
      - master
      - developer
  pull_request:
    branches:
      - main
      - master
      - developer
      - hotfix

jobs:
  trabalho1:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 1
        run: echo "executando o primeiro passo"
      - name: Passo 2
        run: echo "Executando o segundo passo"
      - name: Passo 3 
        run: echo "Executando o terceiro passo"

  trabalho2:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 4
        run: echo "executando o primeiro passo"
      - name: Passo 5
        run: echo "Executando o segundo passo"
      - name: Passo 6 
        run: echo "Executando o terceiro passo"

  trabalho3:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 7
        run: echo "executando o primeiro passo"
      - name: Passo 8
        run: echo "Executando o segundo passo"
      - name: Passo 9 
        run: echo "Executando o terceiro passo"
